version: '3.8'

services:
  api:
    build: .
    container_name: shopify-discount-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SHOPIFY_DOMAIN=${SHOPIFY_DOMAIN}
      - SHOPIFY_ADMIN_API_TOKEN=${SHOPIFY_ADMIN_API_TOKEN}
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_SECRET_KEY=${SHOPIFY_SECRET_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/discounts"]
      interval: 30s
      timeout: 10s
      retries: 3
